### ISSUE TITLE
Materials

### ISSUE THREAD

**Issue by zhao1995chen** [zhao1995chen/final-project-of-2020-training-class#27]
- game icons

**Comment by ISTPTW2020** [comment]
要svg or png?

**Comment by zhao1995chen** [comment]
有去背都可

**Comment by ISTPTW2020** [comment]
https://drive.google.com/drive/folders/15YGv3u5YYCWg3V3zA4RKZUGsynicWh_S?usp=sharing
Flaticon有限制下載量，我今天只能下載這些、明天繼續下載。
照著網路上說的上傳檔案上來但不知道有沒有成功，所以上傳一份到google drive如上連結。
